### ISSUE TITLE
Unable to Connect via ZeroConf Android App

### ISSUE THREAD

**Issue by colinnuk** [tkem/mopidy-mobile#108] opened 2015-06-11 20:22 UTC
What was the reason for removing the option to connect to a server with a hostname? I can't seem to get my ZeroConf setup working at all (and hence the app is useless), whereas it was working fine pre 1.0 on the Android app.

**Comment by tkem** [comment] 2015-06-12 03:19
There have been a lot of internal changes between v0.9.3 (the last version available as an app) and v1.0, so the server management stuff would have to be rewritten, and this just didn't make it for v1.0.
However, I plan to re-add this feature in the near future, so please bear with me ;-)

In the mean time, you could either
- install the Mopidy-Mobile v1.0 Web extension and use the Web client (there's not much difference, anyway)
- continue using Mopidy-Mobile Beta v0.9.3, which is still available on Google Play for members of the Mopidy announcement list.

To see whether ZeroConf-releated problems are caused by Mopidy-Mobile or your server/network settings, may I ask you try a third-party ZeroConf browser app on your device and see if it reports the `_mopidy-http` service? I'd personally recommend `ZeroConf Browser` [https://play.google.com/store/apps/details?id=com.melloware.zeroconf&hl=en], but there are a couple of ZeroConf/Bonjour apps available for free on Google Play.

**Comment by colinnuk** [comment] 2015-06-14 07:36
OK thanks - turns out I had ZeroConf issues, so not related to your app, though I still think it's useful to have the option to manually enter hostname:port settings!

Thanks for the great work.

**Comment by tkem** [comment] 2015-06-14 08:13
You're right, of course ;-)
Watch #109 for progress on this...

**Comment by tkem** [comment] 2015-06-14 08:15
Leaving this open so other users can find some hints on this, and until #109 gets implemented and/or more info is provided in README or app itself.

**Comment by tkem** [comment] 2015-06-16 17:48
Closing for now. May be reopened if other ZeroConf issues are found.

**Closed by tkem** 2015-06-16 17:48 UTC
