### ISSUE TITLE
LibraryProvider.browse not called when traversing up directory hierarchy

### ISSUE THREAD

**Issue by jcass77** [tkem/mopidy-mobile#158] opened 2016-01-02 19:39 UTC
When traversing a library that contains multiple sub-directories, the ```LibraryProvider.browse()``` method is called navigating down, but not called when clicking on the 'back arrow' as one traverses back up to the root directory again.

As a result, Mopidy-Mobile will sometimes display an outdated version of the directory hierarchy (e.g. if an adjacent directory was deleted while the user was playing a track in another directory).

**Comment by tkem** [comment] 2016-01-02 19:55
That's by design. When browsing "down" the hierarchy, ionic views are cached. You can always pull-to-refresh to update a browsing view, though that won't help much if a parent directory gets deleted.

**Comment by tkem** [comment] 2016-01-02 19:59
I also tested a non-cached implementation, and caching makes for a significant usability improvement due to reduced latency, IMHO. Whether caching should be enabled *could* be made a user-config, but only with (I guess) significant amount of work and increased complexity. So I won't consider it at the moment.

**Comment by jcass77** [comment] 2016-01-02 20:16
I wasn't aware of the *pull-to-refresh* feature - is that documented anywhere?

Personally I think just doing a manual refresh as described above is fine.

Just out of interest: is the performance improvement that you refer to as a result of not having to make another time-consuming backend call or just due to network transfer and rendering on the frontend?

I've implemented caching on a back-end that I am working on which also improves usability quite a bit. The advantage of implementing caching in the backend (if network transfer / rendering is not an issue) is that you can detect the types of changes that should invalidate the cache.

**Comment by tkem** [comment] 2016-01-02 20:32
Well, *documentation* is one area where MoMo clearly could be improved ;-)

As for the actual performance improvement, that depends on backend and list size, of course. 

However, feedback from several "test users" suggests that the impact is partly psychological - like, anybody accepts that loading an "Artists" or "Albums" view with several hundred entries takes some time to load, but after navigating to a a certain list entry and then going "back" to the long list should happen almost instantly. Even for small lists with a local backend, the network round trip alone caused some raised eyebrows, especially if the loading "spinner" showed up.

**Comment by tkem** [comment] 2016-01-05 08:45
Closing this, since documentation is an entirely different issue.

**Closed by tkem** 2016-01-05 08:45 UTC
Labels: question
